### PR TITLE
Using shiftwidth()

### PR DESCRIPTION
**Pull request by ryunix**

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by pago88** [comment]
Question about this fix. Fairly new to vim and emmet, so may be dumb question, but where is the function shiftwidth()? 
<c-y>, throws an error, mainly saying Unknown function: shiftwidth
Attached a quick screenshot. 
This is my first time trying emmet out, but I reversed this change to what it was before, and that worked no problem. Am I missing something here?

screen shot 2016-04-25 at 12 38 58 pm

**Comment by mattn** [comment]
fixed https://github.com/mattn/emmet-vim/commit/b4b21450f2c89b8abf41aa4bd011c2b27d1c241d

**Comment by ryunix** [comment]
shiftwidth() is builtin function. (from 7.3.694)
I did not think old version, sorry.

**Pull request merged**
